### ISSUE TITLE
consider the case when wallet account is deleted

### ISSUE THREAD

**Issue by amgando** [vbstreetz/downtown-stimulus#1]
the application does not handle the case when i've previously logged in with an account (localstorage for this URL includes a NEAR Wallet account) but that account has since been deleted.

![image](https://user-images.githubusercontent.com/24913/82305249-11d57e80-99c6-11ea-96ee-7547c43adb8b.png)

**Comment by vbstreetz** [comment]
Nice catch .... on it 👍

**Comment by vbstreetz** [comment]
Added a handler for this 👍
